arguments:
  parameters:
    - name: fetch-new-images-username
      value: 1mihirpandya
    - name: fetch-new-images-organization
      value: 1mihirpandya
    - name: fetch-new-images-token-secret-name
      value: dockerhub-auth-secret
    - name: run-tests-succeed
      value: true
    - name: dev-appname
      value: guestbook-app-dev
    - name: staging-appname
      value: rollout-env4
    - name: dev-revision
      value: master
    - name: staging-revision
      value: main
