arguments:
  parameters:
    - name: deploy-application-argocd-version
      value: v2.0.5
    - name: deploy-application-application-name
      value: test
    - name: deploy-application-revision
      value: master
    - name: deploy-application-flags
      value: --
    - name: deploy-application-argocd-server-address
      value: greenops-cd-argocd-server.argocd.svc.cluster.local
    - name: deploy-application-argocd-credentials-secret
      value: argocd-user
