apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deploy-guestbook
spec:
  entrypoint: provision-customer
  templates:
  - name: provision-customer
    dag:
      tasks:
      - name: provision-cluster
        templateRef:
          name: root
          template: suspend
      - name: configure-cluster
        templateRef:
          name: root
          template: suspend
        dependencies: [provision-cluster]
      - name: deploy-app
        templateRef:
          name: root
          template: suspend
        dependencies: [configure-cluster]
