arguments:
  parameters:
    - name: fetch-new-images-username
      value: 1mihirpandya
    - name: fetch-new-images-organization
      value: greenopsinc
    - name: fetch-new-images-token-secret-name
      value: dockerhub-auth-secret
    - name: decide-new-release-name-image-names
      value: output-fetch-new-images/parameters/image-names-list
    - name: decide-new-release-name-image-tags
      value: output-fetch-new-images/parameters/image-tags-list
    - name: create-new-branch-branch-name
      value: output-decide-new-release-name/parameters/release-version
    - name: create-new-branch-github-repo
      value: mihirpandya-greenops/helm-chart-copy
    - name: create-new-branch-path-to-file
      value: greenops/values.yaml
    - name: create-new-branch-github-branch
      value: main
    - name: create-new-branch-image-names
      value: output-fetch-new-images/parameters/image-names-list
    - name: create-new-branch-updated-revisions
      value: output-fetch-new-images/parameters/image-tags-list
    - name: create-new-branch-github-credentials-secret
      value: github-pat
    - name: update-argo-app-argocd-version
      value: v2.0.5
    - name: update-argo-app-application-name
      value: test-app
    - name: update-argo-app-revision
      value: output-decide-new-release-name/parameters/release-version
    - name: update-argo-app-flags
      value: --
    - name: update-argo-app-argocd-server-address
      value: argo-cd-argocd-server.argocd.svc.cluster.local:80
    - name: update-argo-app-argocd-credentials-secret
      value: argocd-user
