arguments:
  parameters:
    - name: fetch-new-images-username
      value: 1mihirpandya
    - name: fetch-new-images-organization
      value: 1mihirpandya
    - name: fetch-new-images-token-secret-name
      value: dockerhub-auth-secret
    - name: decide-new-release-name-image-names
      value: output-fetch-new-images/parameters/image-names-list
    - name: decide-new-release-name-image-tags
      value: output-fetch-new-images/parameters/image-tags-list
    - name: create-new-branch-branch-name
      value: output-decide-new-release-name/parameters/release-version
    - name: create-new-branch-github-repo
      value: mihirpandya-greenops/argocd-example-apps
    - name: create-new-branch-path-to-file
      value: guestbook/guestbook-ui-deployment.yaml
    - name: create-new-branch-github-branch
      value: master
    - name: create-new-branch-image-names
      value: output-fetch-new-images/parameters/image-names-list
    - name: create-new-branch-updated-revisions
      value: output-fetch-new-images/parameters/image-tags-list
    - name: create-new-branch-github-credentials-secret
      value: github-pat
    - name: deploy-revision-argocd-version
      value: v2.0.5
    - name: deploy-revision-application-name
      value: guestbook-app
    - name: deploy-revision-revision
      value: master
    - name: deploy-revision-flags
      value: --
    - name: deploy-revision-argocd-server-address
      value: argocd.greenops.io
    - name: deploy-revision-argocd-credentials-secret
      value: argocd-user
    - name: run-tests-succeed
      value: false
    - name: send-failure-message-webhook-url
      value: https://hooks.slack.com/services/T02FT1S6X62/B03TM27514K
    - name: send-failure-message-webhook-token-secret
      value: slack-secret
    - name: send-failure-message-message
      value: "Tests for new release failed."
    - name: create-and-wait-for-pr-github-repo
      value: mihirpandya-greenops/argocd-example-apps
    - name: create-and-wait-for-pr-github-branch
      value: master
    - name: create-and-wait-for-pr-github-credentials-secret
      value: github-pat
