apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: release-new-charts
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: fetch-new-image-info
        templateRef:
          name: fetch-image-tags
          template: dockerhub
        arguments:
          parameters:
          - name: username
            value: "{{workflow.parameters.fetch-new-image-info-username}}"
          - name: organization
            value: "{{workflow.parameters.fetch-new-image-info-organization}}"
          - name: token-secret-name
            value: "{{workflow.parameters.fetch-new-image-info-token-secret-name}}"
