apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deploy-to-customers
spec:
  entrypoint: entry
  templates: 
  - name: entry
    dag:
      tasks:
      - name: deploy-to-customer-1
        templateRef:
          name: argocd-step
          template: argocd-sync-and-wait
        arguments:
          parameters:
          - name: argocd-version
            value: "{{workflow.parameters.deploy-to-customer-1-argocd-version}}"
          - name: application-name
            value: "{{workflow.parameters.deploy-to-customer-1-application-name}}"
          - name: revision
            value: "{{workflow.parameters.deploy-to-customer-1-revision}}"
          - name: flags
            value: "{{workflow.parameters.deploy-to-customer-1-flags}}"
          - name: argocd-server-address
            value: "{{workflow.parameters.deploy-to-customer-1-argocd-server-address}}"
          - name: argocd-credentials-secret
            value: "{{workflow.parameters.deploy-to-customer-1-argocd-credentials-secret}}"
      - name: deploy-to-customer-2
        templateRef:
          name: argocd-step
          template: argocd-sync-and-wait
        arguments:
          parameters:
          - name: argocd-version
            value: "{{workflow.parameters.deploy-to-customer-2-argocd-version}}"
          - name: application-name
            value: "{{workflow.parameters.deploy-to-customer-2-application-name}}"
          - name: revision
            value: "{{workflow.parameters.deploy-to-customer-2-revision}}"
          - name: flags
            value: "{{workflow.parameters.deploy-to-customer-2-flags}}"
          - name: argocd-server-address
            value: "{{workflow.parameters.deploy-to-customer-2-argocd-server-address}}"
          - name: argocd-credentials-secret
            value: "{{workflow.parameters.deploy-to-customer-2-argocd-credentials-secret}}"
