apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ansible
spec:
  templates:
  - name: run-ansible-playbook
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        print("Running EC2 deployment")
